title: Pet Hub Local
description: Pet Hub Local the local instance of the Sure Pet Care 'Connect' series of IoT enabled devices.
domain: pethublocal.github.io  
url: "https://pethublocal.github.io"
baseurl: ""
twitter_username: plambrechtsen
github_username:  plambrechtsen

# Build settings
markdown: GFM
theme: minima

plugins:
  - jemoji